config/routes.rb
Checkin::Application.routes.draw do
  get "attendees/new"
  post "attendees/create"

  resources :events, :attendees
  devise_for :users

  get  "checkin" => "events#checkin_page"
  post "checkin" => "events#checkin"

  get "gift/:gift" => "events#gift"

  root :to => "home#index"
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  mount_uploader :gift, GiftUploader

  before_save :to_utc, :create_end_datetime, :add_bounds_to_locations, :save_original_file_name
  
  validates :name, :presence => true
  validates :venue, :presence => true
  validates :address, :presence => true
  validates :latitude,  :presence => true
  validates :longitude, :presence => true

  def to_utc
    # Set the timezone
    Time.zone = timezone

    # Get the offset in hours
    offset = Time.zone.utc_offset/60/60

    # Invert the sign of the offset to we can get it back to UTC
    offset *= -1

    # Store the time in UTC
    self.datetime += offset.hours
  end

  def create_end_datetime
    self.end_datetime = datetime + 2.hours
  end
  
  def add_bounds_to_locations
    self.min_latitude  = latitude - 0.001
    self.max_latitude  = latitude + 0.001
    self.min_longitude = longitude - 0.001
    self.max_longitude = longitude + 0.001
  end

  def original_file_name
    self.gift_name = self.file.original_name
  end

  def self.find_by_time_and_location(time, params)
    self.where(["min_longitude <= ? AND max_longitude >= ? AND min_latitude <= ? AND max_latitude >= ? AND end_datetime > ? AND datetime < ?", params[:longitude], params[:longitude], params[:latitude], params[:latitude], time, time]).first
  end

  def self.find_by_time(time)
    self.where(["end_datetime > ? AND datetime < ?", time, time]).first
  end

  def self.find_by_location(params)
    self.where(["min_longitude <= ? AND max_longitude >= ? AND min_latitude <= ? AND max_latitude >= ?", params[:longitude], params[:longitude], params[:latitude], params[:latitude]]).first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me

  has_many :events, :dependent => :destroy

  validates :username, :presence => true,
                       :format => { :with => /^[a-zA-Z0-9]+$/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def new
  end

  def create
    @attendee = Attendee.new(params[:attendee])
    @event = Event.find(@attendee.event_id)
    GiftMailer.send_gift(@attendee.email, @event).deliver
    redirect_to root_path, notice: 'An email should be sent to you soon.'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = current_user.events
  end

  def new
    @event = current_user.events.new
  end

  def checkin_page
  end

  def checkin
    @event = Event.find_by_time_and_location(Time.zone.now, params[:event])

    if @event
      @email = Attendee.new
      render :layout => false
    else
      # Event not found.
    end
  end

  def gift
    @event = Event.find_by_gift(params[:gift])
    send_file @event.gift.url, :x_sendfile => true
  end

  def create
    @event = current_user.events.new(params[:event])

    if @event.save
      redirect_to events_path, notice: 'Event was created successfully'
    else
      render action: 'new'
    end
  end

  def edit
    @event = current_user.events.find(params[:id])
  end

  def update
    @event = current_user.events.find(params[:id])
    
    if @event.update_attributes(params[:event])
      redirect_to events_url, notice: 'Event was updated successfully'
    else
      render action: 'new'
    end
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy
    redirect_to events_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendees/create.html.haml
%h1 Attendees#create
%p Find me in app/views/attendees/create.html.haml

app/views/attendees/new.html.haml
%h1 Attendees#new
%p Find me in app/views/attendees/new.html.haml

app/views/events/checkin.haml
Please enter your email and we will send you your free stuff!
= form_for @email do |f|
  = f.label :email
  = f.text_field :email
  = f.hidden_field :event, :value => @event.id
  = f.submit

app/views/events/checkin_page.html.haml
:javascript
  $(document).ready(function() {
    find_event();
  });

%p#please_wait Checking your location against current events... please wait.

%p#not_found{:style => "display:none"} Sorry, we could not find an event that's currently taking place at your location.

%p#event_found{:style => "display:none"} Event found...

app/views/events/edit.html.haml
%h1 Events#edit
%p Find me in app/views/events/edit.html.haml

app/views/events/index.html.haml
%h2 Events

%p= link_to 'New event', new_event_path, :class => "btn small success"

- @events.each do |event|
  .event
    %h3= event.name
    %p= event.datetime.strftime("%B %d, %Y at %I:%M %p")
    %p= event.timezone
    %p= event.message

app/views/events/new.html.haml
%h2 New Event 
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@playlist.errors.count, "error")} prohibited this playlist from being saved:"
      %ul
        - @playlist.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field.date
    = f.label :date
    = f.datetime_select :datetime, :ampm => true
  .field
    = f.label :time_zone
    = f.time_zone_select :timezone
  .field
    = f.label :venue
    = f.text_field :venue
  .field
    = f.label :address
    = f.text_field :address, :onblur => "geocode();"
  .field
    = f.label :message
    = f.text_field :message
  .field
    = f.label :gift
    = f.file_field :gift
  .hidden_fields
    .map_container
      #map_canvas{:style => "height: 400px; width: 400px;"}
    .field
      = f.label :latitude
      = f.text_field :latitude
    .field
      = f.label :longitude
      = f.text_field :longitude

  .actions
    = f.submit 'Save', :class => "btn primary"

app/views/home/index.html.haml
%h1 What is Checkin?
%p Checkin in an app inspired by Foursquare and Facebook's Location posts but with a slight twist. Instead of people being able to check in at a location whenever, an artist that is playing a show at a venue will create an event at a specific time and users can only check in at that time.
%p There's more to it than just checking in at specific times. The creators of the event can add a message to display to the user and upload a song to give to the user when they check in. The message and file are emailed to the person who checked in as an incentive for doing so.
%p To get started #{link_to 'log in', new_user_session_path} or #{link_to 'register', new_user_registration_path}.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Checkin
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    #header
      %h1 Checkin
      %ul#nav
        - if user_signed_in?
          %li= link_to 'manage events', events_path
          %li= link_to 'settings', edit_user_registration_path
          %li= link_to 'log out', destroy_user_session_path, :method => :delete
        - else
          %li= link_to 'register', new_user_registration_path
          %li= link_to 'login', new_user_session_path

    #content
      = yield

    #footer
      &copy; Tomer Elmalem